### ISSUE TITLE
Incompatible version with VTK 9.7

### ISSUE THREAD

**Issue by valeperseo** [euratom-software/calcam#184]
In a freshly installed environment, I got this error when trying to load a png image:

CALCAM ERROR REPORT
===================

This file was generated by Calcam to help report/debug an unhandled exception.
To report the error, please go to:

      github.com/euratom-software/calcam/issues

and open an issue describing when the error happened, and attach this file.

DIAGNOSTIC INFORMATION
----------------------

Platform:       linux
Python version: 3.12.14 (main, Sep  2 2026, 23:27:36) [GCC 15.3.0]
Calcam version: 2.18.0
VTK version:    9.7.0
OpenCV version: 5.0.0
PyQt version:   5.15.14

Traceback (most recent call last):
  File "/home/IPP-HGW/vape/miniforge3/envs/calcam/lib/python3.12/site-packages/calcam/gui/core.py", line 496, in load_image
    self.on_load_image(newim)
  File "/home/IPP-HGW/vape/miniforge3/envs/calcam/lib/python3.12/site-packages/calcam/gui/fitting_calib.py", line 674, in on_load_image
    self.interactor2d.set_image(self.calibration.get_image(coords='Display'),n_subviews = self.calibration.n_subviews,subview_lookup = self.calibration.subview_lookup)
  File "/home/IPP-HGW/vape/miniforge3/envs/calcam/lib/python3.12/site-packages/calcam/gui/vtkinteractorstyles.py", line 864, in set_image
    self.renderer.AddActor2D(self.image_actor)
    ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'vtkmodules.vtkRenderingOpenGL2.vtkOpenGLRenderer' object has no attribute 'AddActor2D'. Did you mean: 'AddActor'?

**Comment by valeperseo** [comment]
First attempt: environment created with instruction python=3.12 and calcam install with pip --> error 

Second attempt: I deleted the environment, created a new one with python = 3.12.0 and installed calcam with mamba --> it works!

**Comment by valeperseo** [comment]
Actually, there are still problems... When trying to save the calibration I get

CALCAM ERROR REPORT
===================

This file was generated by Calcam to help report/debug an unhandled exception.
To report the error, please go to:

      github.com/euratom-software/calcam/issues

and open an issue describing when the error happened, and attach this file.


DIAGNOSTIC INFORMATION
----------------------

Platform:       linux
Python version: 3.12.0 | packaged by conda-forge | (main, Oct  3 2023, 08:43:22) [GCC 12.3.0]
Calcam version: 2.17.0
VTK version:    9.6.2
OpenCV version: 4.13.0
PyQt version:   6.11.0

Traceback (most recent call last):
  File "/home/IPP-HGW/vape/miniforge3/envs/calcam/lib/python3.12/site-packages/calcam/gui/fitting_calib.py", line 114, in <lambda>
    self.action_save_as.triggered.connect(lambda: self.save_calib(saveas=True))
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/IPP-HGW/vape/miniforge3/envs/calcam/lib/python3.12/site-packages/calcam/gui/fitting_calib.py", line 1723, in save_calib
    self.calibration.save(self.filename)
  File "/home/IPP-HGW/vape/miniforge3/envs/calcam/lib/python3.12/site-packages/calcam/calibration.py", line 1113, in save
    self.set_detector_window(None)
  File "/home/IPP-HGW/vape/miniforge3/envs/calcam/lib/python3.12/site-packages/calcam/calibration.py", line 546, in set_detector_window
    self.set_subview_mask(self.native_subview_mask,subview_names=self.native_subview_names,coords='Original',keep_models=True)
                          ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Calibration' object has no attribute 'native_subview_mask'. Did you mean: 'get_subview_mask'?

**Comment by ssilburn** [comment]
Thanks for reporting! 

On the first issue: Looks like that's caused by a VTK change in v9.7 that I didn't know was coming (my fault, they did announce it) - so I need to update calcam to work with VTK 9.7+. Meanwhile using a python environment with an older (<9.7) VTK version should work fine, as you found.

On the second problem - that's a Calcam bug but has already been fixed in the newest version 2.18 (issue #181), not 100% sure why mamba gave you 2.17 instead. If you can use pip with that environment, `pip install --no-deps calcam==2.18.0`  should give a combination where everything is working until I fix the VTK 9.7 compatibility.

**Comment by ssilburn** [comment]
OK, should be all fixed in new release v2.18.1!
